# Site settings
baseurl = "https://unruffled-fermat-5065aa.netlify.app/"
languageCode = "en-us"
title = "StratSec.info"
theme = "agency"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "StratSec.info"
  description = "Strategic Security Consulting Services LLC"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = true

  # Enable the BSidesATL Twitter Card image
  #socialCard = true

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "stratsec.info"
    #Optional logo as brand stored in img/
    logo = "logo.svg"
    services = "Our Services"
    #vciso = "vCISO services"
    schedule = "Schedule a consult"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Information Security Consulting from an industry and academic expert"
    subtitle = "Strategic Security Consulting Services"

    #[[params.hero.links]]
    #  link = "https://ti.to/bsidesatl/bsidesatl2020/"
    #  text = "Tickets"


    [params.services]
        enable = true
        # Possibility to center items
        center = true
        title = "Our amazing speakers"
        subtitle = "Without them, we'd just be drinking coffee and eating lunch all day."
        #description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

        # All speakers member's pictures are stored under 'static/img/speakers'.
        # Replace them with your own too.
        # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
        [[params.services.members]]
          name = "Dave Shackleford"
          position = "Keynote: Software-Defined Everything, and What That Means to Security"
          company = "Voodoo Security"
          bio = """Dave is the CEO and Principal Consultant with Voodoo Security, and has consulted with hundreds of organizations in the areas of security, regulatory compliance, and network architecture and engineering. Dave is also Lead Faculty at IANS, a SANS analyst, instructor, and course author, and a board member with the SANS Technology Institute. He is a VMware vExpert, and has extensive experience designing and configuring secure virtualized infrastructures. He's the author of the Sybex book ""Virtualization Security: Protecting Virtualized Environments"", leads the Atlanta chapter of the Cloud Security Alliance, and co-chairs the CSA Top Threats to Cloud Working Group. Dave has previously worked as CSO for Configuresoft, CTO for the Center for Internet Security, and has also worked as a security architect, analyst, and manager for several Fortune 500 companies."""
          social = [
           ["fa-twitter", "https://twitter.com/daveshackleford"],
           ["fa-twitter", "https://twitter.com/voodoosecurity"],
          ]
        [[params.services.members]]
          name = "Amber Welch"
          position = "Data Access Rights Exploits under New Privacy Laws"
          bio = """Until she’s accepted for a Mars mission, Amber Welch is pursuing the advancement of personal information privacy and data protection as a Privacy Technical Lead for Schellman & Company. Amber has been assessing corporate privacy compliance programs for the past year and prior to that, managed security and privacy governance for a suite of SaaS products. She has previously worked in companies creating ERP, CRM, event planning, and biologics manufacturing software."""
          social = [
           ["fa-twitter", "https://twitter.com/MsAmberWelch"],
          ]
          [[params.services.members]]
            name = "vCISO Services"
            position = "with our vCISO service you retain a board-level resource who can ‘virtually sit inside your company’ and manage your security strategy, budget, review of risks and regulatory programs."
            #bio = """Until she’s accepted for a Mars mission, Amber Welch is pursuing the advancement of personal information privacy and data protection as a Privacy Technical Lead for Schellman & Company. Amber has been assessing corporate privacy compliance programs for the past year and prior to that, managed security and privacy governance for a suite of SaaS products. She has previously worked in companies creating ERP, CRM, event planning, and biologics manufacturing software."""
            #social = [
             #["fa-twitter", "https://twitter.com/MsAmberWelch"],
            ]

  [params.services]
          enable = true
          # Possibility to center items
          center = true
          # Optional sponsor title specifying the involvement
          title = "Our Services"

  [[params.services.service]]
  title = "vCISO Service"
  subtitle = "with our vCISO service you retain a board-level resource who can ‘virtually sit inside your company’ and manage your security strategy, budget, review of risks and regulatory programs."
  text = '''
  Very nice text goes here in the config file
  '''

  [[params.services.service]]
  title = "Service2"
  subtitle = "with our vCISO service you retain a board-level resource who can ‘virtually sit inside your company’ and manage your security strategy, budget, review of risks and regulatory programs."
  text = '''
  Very nice text goes here in the config file
  '''

  # vciso section
  [params.vciso]
    enable = false
    title = "vCISO Service"
    subtitle = "with our vCISO service you retain a board-level resource who can ‘virtually sit inside your company’ and manage your security strategy, budget, review of risks and regulatory programs."
    #text = '''
    #Very nice text goes here in the config file
    #'''

    # schedule section
  [params.schedule]
    enable = true
    title = "Schedule a free 30-minute consult"

  # Footer section
  [params.footer]
    enable = true
    copyright = ""

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/AndyGreenPhD"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-github"
      link = "https://github.com/AndyGreenPhD"
      title = "Github"
