# Site settings
baseurl = "https://unruffled-fermat-5065aa.netlify.app/"
languageCode = "en-us"
title = "StratSec.info"
theme = "agency"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "StratSec.info"
  description = "Strategic Security Consulting Services LLC"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = true

  # Enable the BSidesATL Twitter Card image
  #socialCard = true

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "stratsec.info"
    #Optional logo as brand stored in img/
    logo = "logo.svg"
    services = "Our Services"
    #vciso = "vCISO services"
    schedule = "Schedule a consult"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Information Security consulting from industry and academic experts"
    subtitle = "Strategic Security Consulting Services"

  [params.services]
        enable = true
        # Possibility to center items
        center = true
        title = "Service Offerings"
        subtitle = "Below are a list of our most frequently requested services.  If you don't see a service you're looking for, schedule a consult to discuss your needs."

        [[params.services.service]]
            name = "vCISO Services"
            description = "with our vCISO service you retain a board-level resource who can ‘virtually sit inside your company’ and manage your security strategy, budget, review of risks and regulatory programs."

        [[params.services.service]]
            name = "Advisory services"
            description = "We provide ad-hoc advisory services to boards, leadership teams, and others on security related items."

        [[params.services.service]]
            name = "Security program assessment"
            description = "Ensure your organizational security function is appropriately staffed, resourced and situated."

        [[params.services.service]]
            name = "Security Risk Assessment Services"
            description = "We work with your team to develop an effective information security risk management program.  A risk assessment is important in building an information security program.  Risk management and risk assessment activities will take into account people, business processes (information handling), and technology."

    # schedule section
  [params.schedule]
    enable = true
    title = "Schedule a free 30-minute consult"

  # Footer section
  [params.footer]
    enable = true
    copyright = ""

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/AndyGreenPhD"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-github"
      link = "https://github.com/AndyGreenPhD"
      title = "Github"
